name: Run Training Pipeline

on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
      - "LICENSE"

permissions:
  id-token: write
  contents: read

jobs:
  start-runner:
    name: Start the self-hosted EC2 runner
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Start EC2 runner
        id: start-ec2-runner
        uses: machulav/ec2-github-runner@v2
        with:
          mode: start
          github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          ec2-image-id: ami-03d3eec31be6ef6f9
          ec2-instance-type: t2.micro
          subnet-id: subnet-0aa14d10459ff4e19
          security-group-id: sg-056fde642ead9d50d

    outputs:
      label: ${{ steps.start-ec2-runner.outputs.label }}
      ec2-instance-id: ${{ steps.start-ec2-runner.outputs.ec2-instance-id }}

  run-train:
    name: Run training pipeline
    needs: start-runner
    runs-on: ${{ needs.start-runner.outputs.label }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Update os packages and install other requirements
        run: |
          sudo apt update -y
          sudo apt-get update -y
          sudo apt upgrade -y 
          sudo apt install aws-cli -y
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # - name: Install the requirements
      #   run: |
      #     pip3 install -r requirements.txt

      - name: Run the training pipeline code
        run: |
          aws sts get-caller-identity --query Account --output text > text.txt
